<a href="https://colab.research.google.com/github/dawit3000/selam/blob/master/Copy_of_matrixbasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sympy import *
init_printing()

In [ ]:
A = Matrix([[-3,-2,0,2,0],[1,1,-1,1,1],[1,3,-1,1,5]]) ## This defines matrix A
A  ## This Displays A

⎡-3  -2  0   2  0⎤
⎢                ⎥
⎢1   1   -1  1  1⎥
⎢                ⎥
⎣1   3   -1  1  5⎦

In [ ]:
A.echelon_form()  ## This generates the row-echelon form (ref) of matrix A

⎡1  2   -1  1  3 ⎤
⎢                ⎥
⎢0  -1  0   0  -2⎥
⎢                ⎥
⎣0  0   0   0  0 ⎦

In [ ]:
A.rref()  ## This generates the reduced row-echelon (rref) of matrix A

⎛⎡1  0  -1  1  -1⎤        ⎞
⎜⎢               ⎥        ⎟
⎜⎢0  1  0   0  2 ⎥, (0, 1)⎟
⎜⎢               ⎥        ⎟
⎝⎣0  0  0   0  0 ⎦        ⎠

In [ ]:
D=Matrix([[1,2,-1,1],[1,1,-1,1],[1,3,-1,1]])
b = Matrix([[3],[4],[1],[2]])
D


⎡1  2  -1  1⎤
⎢           ⎥
⎢1  1  -1  1⎥
⎢           ⎥
⎣1  3  -1  1⎦

In [ ]:
b

⎡3⎤
⎢ ⎥
⎢4⎥
⎢ ⎥
⎢1⎥
⎢ ⎥
⎣2⎦

In [ ]:
D*b

⎡12⎤
⎢  ⎥
⎢8 ⎥
⎢  ⎥
⎣16⎦

In [ ]:
C = Matrix([[1,3,6],[2,7,14],[0,2,5]]) ## Defines matrix C
C.inv()  ## The inverse of matrix C

⎡ 7   -3  0 ⎤
⎢           ⎥
⎢-10  5   -2⎥
⎢           ⎥
⎣ 4   -2  1 ⎦

In [ ]:
M = Matrix([[1,3,6],[2,7,14],[0,2,5]])
M

⎡1  3  6 ⎤
⎢        ⎥
⎢2  7  14⎥
⎢        ⎥
⎣0  2  5 ⎦

In [ ]:
M.rref()

⎛⎡1  0  0⎤           ⎞
⎜⎢       ⎥           ⎟
⎜⎢0  1  0⎥, (0, 1, 2)⎟
⎜⎢       ⎥           ⎟
⎝⎣0  0  1⎦           ⎠

In [ ]:
M.echelon_form()

⎡1  3  6⎤
⎢       ⎥
⎢0  1  2⎥
⎢       ⎥
⎣0  0  1⎦

In [ ]:
A.inv() * b

In [ ]:
B = Matrix([[1,3,4],[2,5,2]])
B

⎡1  3  4⎤
⎢       ⎥
⎣2  5  2⎦

In [ ]:
B.nullspace()

⎡⎡14⎤⎤
⎢⎢  ⎥⎥
⎢⎢-6⎥⎥
⎢⎢  ⎥⎥
⎣⎣1 ⎦⎦

In [ ]:
B.columnspace()

⎡⎡1⎤  ⎡3⎤⎤
⎢⎢ ⎥, ⎢ ⎥⎥
⎣⎣2⎦  ⎣5⎦⎦

In [ ]:
## Calculate eigenvalues and eigenvectors

# Import numpy
import numpy as np

# Define a square matrix
A = np.array([[5,-10,-5],
              [2,14,2], [-4,-8,6]])
print("")
print("Here are the outputs:")
print("")
print("Matrix A:")
print(A)

# Calculate eigenvalues and eigenvectors where eigenvectors is a matrix where each column is an eigenvector corresponding to the eigenvalue in the same position.
eigenvalues, eigenvectors = np.linalg.eig(A)

# Print results
print("")
print("Eigenvalues:")
print(eigenvalues)
print("")
print("Eigenvectors (as columns):")
print(eigenvectors)


Here are the outputs:

Matrix A:
[[  5 -10  -5]
 [  2  14   2]
 [ -4  -8   6]]

Eigenvalues:
[ 5. 10. 10.]

Eigenvectors (as columns):
[[ 7.45355992e-01  7.44760246e-16 -5.22799043e-01]
 [-2.98142397e-01 -4.47213595e-01  5.75730417e-01]
 [ 5.96284794e-01  8.94427191e-01 -6.28661791e-01]]
